# Generated by Django 4.0.3 on 2022-04-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_document_created_at_document_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
