# Generated by Django 4.0.3 on 2022-04-15 16:26
import os

from django.db import migrations, models, connection


def load_data_from_sql(apps, schema_editor):
    file_path = os.path.join(os.path.dirname(__file__), 'init_priority.sql')
    sql_statement = open(file_path, encoding='utf-8').read()
    with connection.cursor() as c:
        c.execute(sql_statement)


class Migration(migrations.Migration):
    dependencies = [
        ('document', '0003_document_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.RunPython(load_data_from_sql),
    ]
